#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
List="$(ls .)"
for i in $List;
do
    names="${i#[0-9]*-}"
    echo "$names"
done
